#!/bin/bash

ID=$(id -u)   # root user or not
R="\e[31m"    # colors indications red green yellow nrmal 
G="\e[32m"
Y="\e[33m"
N="\e[0m"

TIMESTAMP=$(date +%F-%H-%M-%S) # indicated time and date 
LOGFILE="/tmp/$0-$TIMESTAMP.log" # create log file for error validation and store all the content in tmp

echo "script started executing at $TIMESTAMP" &>> $LOGFILE

validate(){

if [ $1 -ne 0 ]
    then 
    echo -e "$2...$R failed $N"
    exit 1
else
    echo -e "$2...$G success $N"
fi 
}
if [ $ID -ne 0 ]
then
    echo -e "$R Error: please run the script with root access $N"
    exit 1 # you can give other then 0
else
    echo " you are the root user"
fi # fi means reverse of if condition end 

dnf module disable nodejs -y &>> $LOGFILE

validate $? "disabling current nodejs"

dnf module enable nodejs:18 -y &>> $LOGFILE

validate $? "enabling nodejs18"

dnf install nodejs -y &>> $LOGFILE

validate $? "installing nodejs"

id roboshop 
if [ $? -ne 0 ]
  then
    useradd roboshop
validate $? "roboshop user creation"
else
    echo -e "roboshop user already exists $Y skipping $N"
fi

mkdir -p /app

validate $? "creating app directory"

curl -o /tmp/cart.zip https://roboshop-builds.s3.amazonaws.com/cart.zip &>> $LOGFILE

validate $? "downloading cart application"

cd /app 

unzip -o /tmp/cart.zip &>> $LOGFILE

validate $? "unzipping cart application"

npm install &>> $LOGFILE

validate $? "installing dependencies"

# use absolute path location, because cart path exists there
cp /home/centos/roboshop-shell/cart-service /etc/systemd/system/cart.service

validate $? "coping cart service file"

systemctl daemon-reload &>> $LOGFILE

validate $? " cart daemon reload"

systemctl enable cart &>> $LOGFILE

validate $? "enabling cart"

systemctl start cart &>> $LOGFILE

validate $? "starting cart"