#!/bin/bash

ID=$(id -u)   # root user or not
R="\e[31m"    # colors indications red green yellow nrmal 
G="\e[32m"
Y="\e[33m"
N="\e[0m"
MONGODB_HOST=mongodb.pradeepstore.online

TIMESTAMP=$(date +%F-%H-%M-%S) # indicated time and date 
LOGFILE="/tmp/$0-$TIMESTAMP.log" # create log file for error validation and store all the content in tmp

echo "script started executing at $TIMESTAMP" &>> $LOGFILE

validate(){

if [ $1 -ne 0 ]
    then 
    echo -e "$2...$R failed $N"
    exit 1
else
    echo -e "$2...$G success $N"
fi 
}
if [ $ID -ne 0 ]
then
    echo -e "$R Error: please run the script with root access $N"
    exit 1 # you can give other then 0
else
    echo " you are the root user"
fi # fi means reverse of if condition end 

dnf module disable mysql -y &>> $LOGFILE

validate $? "disable current mysql version"

cp /home/centos/roboshop-shell/mysql-repo /etc/yum.repos.d/mysql.repo

validate $? "copied mysql repo"

dnf install mysql-community-server -y &>> $LOGFILE

validate $? "installing mysql server"

systemctl enable mysqld &>> $LOGFILE

validate $? "enabling mysql"

systemctl start mysqld &>> $LOGFILE

validate $? "starting mysql"

mysql_secure_installation --set-root-pass RoboShop@1

validate $? "setting mysql root passwoord"
