#!/bin/bash

ID=$(id -u)   # root user or not
R="\e[31m"    # colors indications red green yellow nrmal 
G="\e[32m"
Y="\e[33m"
N="\e[0m"
MONGODB_HOST=mongodb.pradeepstore.online

TIMESTAMP=$(date +%F-%H-%M-%S) # indicated time and date 
LOGFILE="/tmp/$0-$TIMESTAMP.log" # create log file for error validation and store all the content in tmp

echo "script started executing at $TIMESTAMP" &>> $LOGFILE

validate(){

if [ $1 -ne 0 ]
    then 
    echo -e "$2...$R failed $N"
    exit 1
else
    echo -e "$2...$G success $N"
fi 
}
if [ $ID -ne 0 ]
then
    echo -e "$R Error: please run the script with root access $N"
    exit 1 # you can give other then 0
else
    echo " you are the root user"
fi # fi means reverse of if condition end 

dnf module disable nodejs -y &>> $LOGFILE

validate $? "disabling current nodejs"

dnf module enable nodejs:18 -y &>> $LOGFILE

validate $? "enabling nodejs18"

dnf install nodejs -y &>> $LOGFILE

validate $? "installing nodejs"

id roboshop 
if [ $? -ne 0 ]
  then
    useradd roboshop
validate $? "roboshop user creation"
else
    echo -e "roboshop user already exists $Y skipping $N"
fi

mkdir -p /app

validate $? "creating app directory"

curl -o /tmp/user.zip https://roboshop-builds.s3.amazonaws.com/user.zip &>> $LOGFILE

validate $? "downloading user application"

cd /app 

unzip -o /tmp/user.zip &>> $LOGFILE

validate $? "unzipping user application"

npm install &>> $LOGFILE

validate $? "installing dependencies"

cp /home/centos/roboshop-shell/user-service /etc/systemd/system/user.service

validate $? "coping user service file"

systemctl daemon-reload &>> $LOGFILE

validate $? " user daemon reload"

systemctl enable user &>> $LOGFILE

validate $? "enabling user"

systemctl start user &>> $LOGFILE

validate $? "starting user"

cp /home/centos/roboshop-shell/mongodb-repo /etc/yum.repos.d/mongo.repo

validate $? "copying mongodb repo"

dnf install mongodb-org-shell -y &>> $LOGFILE

validate $? " installing mongodb clint"

mongo --host $MONGODB_HOST </app/schema/user.js &>> $LOGFILE

validate $? "loading user data into mongodb"
