#!/bin/bash

ID=$(id -u)   # root user or not
R="\e[31m"    # colors indications red green yellow nrmal 
G="\e[32m"
Y="\e[33m"
N="\e[0m"
MONGODB_HOST=mongodb.pradeepstore.online

TIMESTAMP=$(date +%F-%H-%M-%S) # indicated time and date 
LOGFILE="/tmp/$0-$TIMESTAMP.log" # create log file for error validation and store all the content in tmp

echo "script started executing at $TIMESTAMP" &>> $LOGFILE

validate(){

if [ $1 -ne 0 ]
    then 
    echo -e "$2...$R failed $N"
    exit 1
else
    echo -e "$2...$G success $N"
fi 
}
if [ $ID -ne 0 ]
then
    echo -e "$R Error: please run the script with root access $N"
    exit 1 # you can give other then 0
else
    echo " you are the root user"
fi # fi means reverse of if condition end 

dnf install nginx -y &>> $LOGFILE

validate $? "installing nginx"

systemctl enable nginx &>> $LOGFILE

validate $? "enabling nginx"

systemctl start nginx &>> $LOGFILE

validate $? "starting nginx"

rm -rf /usr/share/nginx/html/* &>> $LOGFILE

validate $? "removed default website"

curl -o /tmp/web.zip https://roboshop-builds.s3.amazonaws.com/web.zip &>> $LOGFILE

validate $? "downloaded web application"

cd /usr/share/nginx/html &>> $LOGFILE

validate $? "moving nginx html direcotart"

unzip -o /tmp/web.zip &>> $LOGFILE

validate $? "unzipping web"

cp /home/centos/roboshop-shell/roboshop-conf /etc/nginx/default.d/roboshop.conf &>> $LOGFILE

validate $? "copied roboshop reverse proxy config"

systemctl restart nginx &>> $LOGFILE

validate $? "restarting ngnix"